name: Schedule Test

on:
  workflow_dispatch:
  schedule:
    - cron: "7,17,27,37,47,57 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test scheduler
        run: |
          echo "Scheduled workflow works"
          date -u
